name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - run: npm install

      - name: ncc build
        run: |
          npx @vercel/ncc build src/index.ts

      - name: commit
        run: |
          git add dist/ArgumentBuilder.d.ts dist/index.d.ts dist/index.js
          if ! git diff --exit-code --quiet
          then
            git config user.name ${{ secrets.USER_NAME }}
            git config user.email ${{ secrets.USER_EMAIL }}
            git commit -m 'commit dist'
            git push origin HEAD:main
          fi
