name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - run: npm install

      - name: ncc build
        run: |
          npx @vercel/ncc build src/main.ts --license licenses.txt

      - name: commit
        run: |
          git add dist/ArgumentBuilder.d.ts dist/licenses.txt dist/index.d.ts dist/index.js
          if ! git diff --exit-code --quiet
          then
            git config user.name gitbub-actions
            git config user.email action@github.com
            git commit -m 'commit dist'
            git push
          fi
